const DATA: any = [
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 55,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 23,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 12,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 55,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 77,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 542,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 12,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 76,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 24,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 52,
      inventory: 10,
      revenue: 10,
   },
   {
      image: '',
      status: 'active',
      product: 'placeholdername',
      sales: 73,
      inventory: 10,
      revenue: 10,
   },
]

export const DATA_COLUMNS: any = [
   {
      Header: '',
      accessor: 'col1',
      disableSortBy: true,
   },
   {
      Header: 'Runner Name',
      accessor: 'product',
      disableSortBy: true,
      type: 'string',
   },
   {
      Header: 'Integrations',
      accessor: 'link',
      disableSortBy: true,
      type: 'link',
   },
   {
      Header: 'Status',
      accessor: 'status',
      disableSortBy: true,
      type: 'mesc',
   },
   {
      Header: 'Last Edited',
      accessor: 'inventory',
      type: 'number',
   },
   {
      Header: 'Created On',
      accessor: 'sales',
      type: 'number',
   },
   {
      Header: 'Runs',
      accessor: 'revenue',
      type: 'number',
   },
   {
      Header: '',
      accessor: 'opt',
      disableSortBy: true,
      type: 'mesc',
   },
]

export default DATA
